import{a as p,i as a,S as b}from"./assets/vendor-38cc1e54.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))n(o);new MutationObserver(o=>{for(const e of o)if(e.type==="childList")for(const u of e.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function s(o){const e={};return o.integrity&&(e.integrity=o.integrity),o.referrerPolicy&&(e.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?e.credentials="include":o.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function n(o){if(o.ep)return;o.ep=!0;const e=s(o);fetch(o.href,e)}})();const L="44768400-50ed818a42c4b3c7dfabdf0f1",w="https://pixabay.com/api/";async function m(t,r=1,s=15){const n=await p.get(w,{params:{key:L,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",page:r,per_page:s}});if(n.status!==200)throw new Error(n.status);return n.data}function g(t,r=!0){const s=document.querySelector(".gallery");if(r&&(s.innerHTML=""),t.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"});return}const n=t.map(e=>`
      <li class="gallery-item">
        <a href="${e.largeImageURL}" class="gallery-item">
          <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy" />
          <div class="info">
            <p class="info-item"><b>Likes</b> ${e.likes}</p>
            <p class="info-item"><b>Views</b> ${e.views}</p>
            <p class="info-item"><b>Comments</b> ${e.comments}</p>
            <p class="info-item"><b>Downloads</b> ${e.downloads}</p>
          </div>
        </a>
    </li>
  `).join("");s.insertAdjacentHTML("beforeend",n),new b(".gallery a",{captionsData:"alt"}).refresh(),r||S()}function S(){const{height:t}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}function y(){document.querySelector(".loader").classList.add("visible")}function h(){document.querySelector(".loader").classList.remove("visible")}function v(){const t=document.querySelector("#search-input");t.value=""}function i(t){const r=document.querySelector("#load-more-btn");t?r.classList.remove("hidden"):r.classList.add("hidden")}let l=1,d="";const c=15,f={form:document.querySelector(".form"),input:document.querySelector(".search-input"),loadMoreButton:document.querySelector("#load-more-btn")};f.form.addEventListener("submit",q);f.loadMoreButton.addEventListener("click",E);async function q(t){t.preventDefault();const r=f.input.value.trim();if(r===""){a.warning({title:"Warning",message:"Please enter a search term!"});return}d=r,l=1,y(),i(!1);try{const{hits:s,totalHits:n}=await m(d,l,c);if(s.length===0){a.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"}),i(!1);return}g(s,!0),v(),s.length<c||l*c>=n?(i(!1),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):i(!0)}catch{a.error({title:"Error",message:"Something went wrong. Please try again!"})}finally{h()}}async function E(){l+=1,y();try{const{hits:t,totalHits:r}=await m(d,l,c);g(t,!1);const s=l*c;i(s<r),s>=r&&(i(!1),a.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch{a.error({title:"Error",message:"Something went wrong. Please try again!"})}finally{h()}}
//# sourceMappingURL=commonHelpers.js.map
